#!/bin/bash
set -eu

# GA SUPERVISOR
# Externally-runnable workflow starter
# This should be called by Supervisor/bin/supervisor

THIS=$( cd $( dirname $0 ) ; /bin/pwd )
SUPERVISOR_HOME=$( cd $THIS/../.. ; /bin/pwd )
source $SUPERVISOR_HOME/workflows/common/sh/utils.sh
LOG_NAME="GA/sv"

usage()
{
  echo "usage: GA/sv [-wv] <SITE> <TEST_SCRIPT>"
}

# Defaults:
WAIT=""
VERBOSITY=0

while getopts "hwv" OPT
do
  case $OPT in
    h)
      usage
      exit
       ;;
    w)
      WAIT="-w"
      ;;
    v)
      (( ++VERBOSITY ))
      ;;
    *)
      # Bash prints an error
      exit 1
  esac
done
shift $(( OPTIND - 1))

if (( ${#} < 2 ))
then
  crash "insufficient arguments!"
fi

SITE=$1
TEST_SCRIPT=$2

sv_path_append $THIS/data

$THIS/swift/workflow.sh $WAIT $SITE $TEST_SCRIPT
