# CFG PRM test-1

# async-search settings

# Note: INIT_SIZE needs to be larger than PROCS-2 for now.
INIT_SIZE=${INIT_SIZE:-3}
MAX_EVALS=${MAX_EVALS:-7}
NUM_BUFFER=${NUM_BUFFER:-1}
MAX_THRESHOLD=${MAX_THRESHOLD:-1}
N_JOBS=${N_JOBS:-1}

#INIT_SIZE=${INIT_SIZE:-300}
#MAX_EVALS=${MAX_EVALS:-550}
#NUM_BUFFER=${NUM_BUFFER:-250}

# INIT_SIZE=${INIT_SIZE:-4}
# MAX_EVALS=${MAX_EVALS:-8}
# NUM_BUFFER=${NUM_BUFFER:-2}

RANDOM_SEED=${RANDOM_SEED:-0}
