# CFG PRM test-1

# async-search settings

# Note: INIT_SIZE needs to be larger than PROCS-2 for now.
INIT_SIZE=${INIT_SIZE:-40000}
MAX_EVALS=${MAX_EVALS:-60000}
NUM_BUFFER=${NUM_BUFFER:-20000}
MAX_THRESHOLD=${MAX_THRESHOLD:-120}

#INIT_SIZE=${INIT_SIZE:-300}
#MAX_EVALS=${MAX_EVALS:-550}
#NUM_BUFFER=${NUM_BUFFER:-250}

# INIT_SIZE=${INIT_SIZE:-4}
# MAX_EVALS=${MAX_EVALS:-8}
# NUM_BUFFER=${NUM_BUFFER:-2}

RANDOM_SEED=${RANDOM_SEED:-0}
