#!/bin/bash
set -eu

# PLOT LOAD SH
# Use this to plot the load data after running extract.sh

THIS=$( readlink --canonicalize $( dirname $0 ) )

SUPERVISOR=$( readlink --canonicalize $THIS/../../.. )
source $SUPERVISOR/workflows/common/sh/utils.sh

SIGNATURE -H "Provide a SUMMARY generated by extract.sh!" \
          SUMMARY - ${*}

cp -uv $SUMMARY $THIS
cd $THIS
jwplot load.{cfg,eps} summary.txt
convert load.{eps,png}
