
# LANGS APP LOCAL

PYTHONHOME=${PYTHONHOME:-"/usr/"}
export PYTHONHOME
PYTHON=${PYTHON:-python}
export LD_LIBRARY_PATH="$PYTHONHOME/lib":$LD_LIBRARY_PATH
export PATH="$PYTHONHOME/bin:$PATH"

COMMON_DIR=$EMEWS_PROJECT_ROOT/../common/python
PYTHONPATH+=":$PYTHONHOME/lib/$PYTHON:"
PYTHONPATH+=":$COMMON_DIR:"
PYTHONPATH+="$PYTHONHOME/lib/$PYTHON/dist-packages"

APP_PYTHONPATH=${APP_PYTHONPATH:-}
PYTHONPATH+=":$APP_PYTHONPATH"

export PYTHONPATH
