PYTHONHOME=${PYTHONHOME:-"/usr/"}
export PYTHONHOME
PYTHON=${PYTHON:-python2.7}
export LD_LIBRARY_PATH="$PYTHONHOME/lib":$LD_LIBRARY_PATH
export PATH="$PYTHONHOME/bin:$PATH"

COMMON_DIR=$EMEWS_PROJECT_ROOT/../common/python
PYTHONPATH+=":$PYTHONHOME/lib/$PYTHON:"
PYTHONPATH+=":$COMMON_DIR:"
PYTHONPATH+="$PYTHONHOME/lib/$PYTHON/dist-packages"
export PYTHONPATH
