
:toc:

= Workflow shell scripts

This is the location for common shell scripting tools for the CANDLE Supervisor Workflows.


== Entry points

Each CANDLE workflow is invoked with a shell script, typically called +test_*.sh site ...+, where the +site+ is +theta+, +summit+, etc.  In this document we will call this the workflow_sh script.

=== Purpose

The purpose of these scripts is:

. Determining the run directory, which is the +TURBINE_OUTPUT+ directory used by Swift/T.

. Set key environment variables and Swift/T options for the system scheduler.  These include +PROCS+, +WALLTIME+, +QUEUE+, +PROJECT+, etc.  *(#20)* These are now set for each site in +sched-site.sh+.

. Loading modules.  *(#20)* These are now set for each site in +env-site.sh+.

. Set key environment variables for Python, R, etc.  These include +PYTHONPATH+, +LD_LIBRARY_PATH+, etc.  These are now set for each site in +env-site.sh+.

. Determining which Swift functions to load.  Swift/T may or may not be configured to use its efficient in-memory Python interpreter for the Benchmarks (because of challenges compiling against the site-provided Python plus deep learning stack).  A shell variable called +SWIFT_IMPL+ denotes the Swift function implementation for the benchmarks.  The value is one of:
+
+"py"+:: We are using in-memory functions (based on +python_persist()+)
+
+"app"+:: We are using Swift +app+ functions (that invoke +python+ as an external program)
+
The https://github.com/ECP-CANDLE/Supervisor/tree/master/workflows#objective-function-guide[objective functions] are in +obj_SWIFT_IMPL.swift+.  Logging functions are in +log_SWIFT_IMPL.swift+.  The script is selected via the use of the +swift-t -i FILE+ feature, which includes +FILE+ before the rest of the Swift workflow.

. Obtain application parameters and pass to the +swift-t+ command line.  These are currently specified in a special section of the workflow_sh.  These arguments are conventionally stored in a Bash variable +CMD_LINE_ARGS+, and passed to the +swift-t+ command; they are then available in the Swift script via +argv()+.

////
. [yellow]#&#9733;# Run swift-t!
////

. Record what happened.  This involves writing additional logs into the TURBINE_OUTPUT directory, particularly to capture settings and provenance that Swift/T cannot.

== Site list

=== Summit

`MED106=/gpfs/alpine/world-shared/med106`

==== `env-summit.sh`

* GCC: 7.5.0
* ROOT: `$MED106/sw/summit/gcc-7.5.0`
* Swift/T: 2022-04-12
* Python: `/sw/summit/open-ce/anaconda-base/envs/open-ce-1.5.2-py39-0`
* R: `$ROOT/R/4.1.3`

== Other shell tools

=== ML wrappers

E.g., site_run_model.sh
