# CFG PRM 1

# mlrMBO settings

# Total iterations
PROPOSE_POINTS=${PROPOSE_POINTS:-3}
MAX_CONCURRENT_EVALUATIONS=${MAX_CONCURRENT_EVALUATIONS:-1}
MAX_ITERATIONS=${MAX_ITERATIONS:-5}
MAX_BUDGET=${MAX_BUDGET:-1800}
DESIGN_SIZE=${DESIGN_SIZE:-30}
PARAM_SET_FILE=${PARAM_SET_FILE:-$EMEWS_PROJECT_ROOT/data/parameter_set.R}
MODEL_NAME="p1b1"

