#!/bin/bash
set -eu

LEAVEOUT_PUNCH_X=$1
LEAVEOUT_PUNCH_Y=$2
FILE_OUTPUT=$3

echo FAKE-UNO.SH: \
     LEAVEOUT_PUNCH_X=$LEAVEOUT_PUNCH_X \
     LEAVEOUT_PUNCH_Y=$LEAVEOUT_PUNCH_Y \
     FILE_OUTPUT=$FILE_OUTPUT | \
  tee $FILE_OUTPUT
