
= Simple C-Python Example

This program tests the use of Python from C.

The program is called `py-eval` .  Its arguments are:

1. Zero or more Python scripts that are executed with no return value.
2. Any number of hyphen tokens `-` , which provides a _New Python Interpreter_ at each point.
3. Any number of sequences `env: K=V`, which sets environment variable `K` to `V` at that point.  Note that you must reset the interpreter with `-` for this to have an effect in Python.
4. The last argument must be:
.. Exactly one Python script that returns a string, which is printed, +
   or
.. the token `0` (zero), which does nothing.

== Versions

This has been tested with Python versions:

* 2.7.10
* 3.6m
* 3.12

== Installation

You may need to set environment variable `PYTHONHOME` at runtime to agree with `PYTHON_HOME` in the Makefile.

To enable MPI, edit the Makefile to set `MPI=1` .

Transcript:

----
# edit Makefile for "Python installation settings"
$ make
$ export PYTHONHOME=...
$ ./py-eval py/import-io.py py/hello.py
----

== Debugging

For more verbose output, provide `-v` .

For extreme verbosity, set environment variable `PYTHONVERBOSE=1` .

== Examples

See examples in the directory `py`.

Hello:
----
$ ./py-eval py/hello.py
----

To test the exception handling capabilities, do:
----
$ ./py-eval py/err.py py/hello.py
----

To test the _New Python Interpreter_ feature, compare:
----
$ cd py
$ ../py-eval x2.py print_x.py hello.py
2
'Hello'
----

with the same thing with added - :

----
$ cd py
$ ../py-eval x2.py - print_x.py hello.py

PYTHON EXCEPTION:
<class 'NameError'>
name 'x' is not defined
py-eval: python code failed.
----

Importing modules:

----
$ ./py-eval py/import-numpy.py 0
----

Setting environment variables:

----
$ ./py-eval -v env: K=3 - py/env_K.py 0
----
