#!/bin/bash
set -eu

# UPF SUPERVISOR
# This should be called by Supervisor/bin/supervisor

THIS=$( cd $( dirname $0 ) ; /bin/pwd )
SUPERVISOR_HOME=$( cd $THIS/../.. ; /bin/pwd )
source $SUPERVISOR_HOME/workflows/common/sh/utils.sh
LOG_NAME="supervisor/UPF"

if (( ${#} < 1 ))
then
  crash "insufficient arguments!"
fi

SITE=$1
TEST_SCRIPT=$2

sv_path_append $THIS/data
sv_path_append $SUPERVISOR_HOME/workflows/common/sh

source_cfg $TEST_SCRIPT

$THIS/swift/workflow.sh $SITE $TEST_SCRIPT
