
= DB-HPO

This describes the use of the DB by Challenge Problem 1.

Challenge Problem 1 is just using categorical hyperparameters, which simplifies the DB problem.

== Tables

=== +hpo_ids+ -- HPO IDs

Each HPO instance (e.g., an mlrMBO run) has an HPO ID.  This is the same as the EMEWS experiment ID.  E.g., +X042+ will have +hpo_id=42+ .

=== +hpo_hyperparam_defns+ -- Hyperparameter definitions

Within an HPO instance, each hyperparameter has a row containing its +param_id+ and a +name+ (e.g., "activation" or "dense_feature_layers").

In the future, this table may be extended to describe non-categorical hyperparameters.

=== +hpo_hyperparam_values+ -- Hyperparameter values

Each possible hyperparameter value has a row in this table.  For hyperparameter name "activation", there are three rows "relu", "tanh", and "sigmoid".  Each row has a unique integer +value_id+.

=== +hpo_samples+ -- Hyperparameter sample results

Each sample (a model training run) will consume a unique set of hyperparameters and produce a row in this table.  The string +hyperparams+ contains a comma-separated list of +value_id+s that point to table +hpo_hyperparam_values+.

== Scripts

db-hpo-init::
Initializes the table schema.  Uses db-hpo-init.py and db-hpo-init.sql .

db-hpo-setup.py::
Populates the tables for an HPO instance.
+
Accepts the HPO ID and a YAML file containing the hyperparameter definitions.
+
Creates entries in +hpo_ids+, +hpo_hyperparam_defns+, and +hpo_hyperparam_values+ for this HPO instance.  After this script, these 3 tables are not change with respect to this HPO ID.

db-hpo-list.py::
Queries the DB to produce human-readable reports.

db-hpo-sample.py::
(Not yet implemented)
Inserts the sample definition and result into table +hpo_samples+.
