
////
You can compile this locally with
$ ../docs/adoc.sh README.adoc
or just view it on GitHub.
////

= Supervisor Workflows

Demonstration workflows for CANDLE.

== auen41_ff on Cooley

*Contacts:* Wozniak and Balaprakash +
*Source:* +git@github.com:ECP-CANDLE/Supervisor.git https://github.com/ECP-CANDLE/Supervisor/tree/master/workflows[/workflows/auen41_ff]+ +
*Systems tested:* http://swift-lang.github.io/swift-t/sites.html#cooley_candle[Cooley]

Add this Swift/T to your +PATH+: +~wozniak/Public/sfw/x86_64/login/swift-t-conda/stc/bin+

=== py-keras.swift

This simply demonstrates that the model can be run from Swift/T +python()+.

We took the Python program https://github.com/ECP-CANDLE/Supervisor/blob/master/workflows/auen41_ff/auen41_ff.py[auen41_ff.py] and turned it into a library that can be imported and run from Swift/T.  The new function entry point is +go()+.  The program still works from the command line

https://github.com/ECP-CANDLE/Supervisor/blob/master/workflows/auen41_ff/py-keras.swift[py-keras.swift] simply loads the module +auen41_ff+ and runs +go()+.

The +go()+ function accepts the directory containing the +breast.train.csv+ and +breast.test.csv+ files.  These can be obtained on Cooley at +~wozniak/Public/data/CANDLE/auen41_ff+ .

The run script that you launch is https://github.com/ECP-CANDLE/Supervisor/blob/master/workflows/auen41_ff/py-keras-cooley.sh[py-keras-cooley.sh] .  The only non-trivial thing here is that we have to set +PYTHONHOME+ for Keras but we cannot let +qsub+ see this variable (or it will fail), so we hide it as +PH+, and send it to Swift via +swift-t -e+.

This obtains settings from https://github.com/ECP-CANDLE/Supervisor/blob/master/workflows/auen41_ff/settings.sh[settings.sh].

Output goes in numbered directories +out-NNN+.

==== Example transcript

----
$ ./py-keras-cooley.sh ~wozniak/Public/data/CANDLE/auen41_ff
TURBINE-COBALT SCRIPT
...
JOB_ID=...
... # Job runs...
TOTAL_TIME=...
# Job completed
# View output:
$ less out-001/output.txt
----
