
////
You can compile this locally with
$ ../docs/adoc.sh README.adoc
or just view it on GitHub.

For compatibility for the GitHub and asciidoc program,
internal links <<.>> have to be specified with headers [[.]]
////

= Supervisor Workflows

Demonstration workflows for CANDLE.

== The Matrix

This is an matrix of workflow capabilities and CANDLE benchmarks.

[options="header"]
|========
| Workflow  | Synth^1^ | AUEN | P1B1 | P1B2
| Invoke^2^ | | <<py-keras.swift>> | |
| Random^3^ | | | |
| Grid^4^
| <<SimpleSweepCommandLine>>  +
  <<SimpleSweepPython>> | | |
| https://github.com/DEAP/deap[DEAP] | | <<AUEN_DEAP>> | |
| Hyperopt  | | | |
| https://github.com/mlr-org/mlrMBO[mlrMBO] | | | |
|========

. _Invoke_ means that we can call this one time from Swift
. _Synth_ means some kind of synthetic task: not a real ML
. Random search
. Grid search

== Demonstrations

[[SimpleSweepCommandLine]]
=== SimpleSweepCommandLine

Demonstrates calling Swift parameter sweep over Python command line tasks.

https://github.com/CODARcode/SwiftExamples/tree/master/SimpleSweepCommandLine[CODARCode/SwiftExamples] SimpleSweepCommandLine

*Systems tested:* Local machine, http://swift-lang.github.io/swift-t/sites.html#_beagle[Beagle]

[[SimpleSweepPython]]
=== SimpleSweepPython

Demonstrates calling Swift parameter sweep over Python in-memory tasks.

http://github.com/CODARcode/SwiftExamples[CODARCode/SwiftExamples] SimpleSweepPython

*Systems tested:* Local machine, http://swift-lang.github.io/swift-t/sites.html#_beagle[Beagle]

=== SimpleSweepPyDB (WIP)

Demonstrates calling Swift parameter sweep over Python in-memory tasks plus inserts to Solr database via pysolr.

http://github.com/CODARcode/SwiftExamples[CODARCode/SwiftExamples] SimpleSweepPyDB

*Systems tested:* WIP: Local machine

[[AUEN_DEAP]]
== AUEN_DEAP

This demo runs an AUEN/Theano evolutionary algorithm.

See the https://github.com/CODARcode/SwiftExamples/tree/master/auen[README here].

*Systems tested:* http://swift-lang.github.io/swift-t/sites.html#_beagle[Beagle]

== auen41_ff on Cooley

*Contacts:* Wozniak and Balaprakash +
*Source:* +git@github.com:ECP-CANDLE/Supervisor.git+ http://github.com/ECP-CANDLE/Supervisor/tree/master/workflows[+/workflows/auen41_ff+] +
*Systems tested:* http://swift-lang.github.io/swift-t/sites.html#cooley_candle[Cooley]



Add this Swift/T to your +PATH+: +~wozniak/Public/sfw/x86_64/login/swift-t-conda/stc/bin+

[[py-keras.swift]]
=== py-keras.swift

This simply demonstrates that the model can be run from Swift/T +python()+.

We took the Python program https://github.com/ECP-CANDLE/Supervisor/blob/master/workflows/auen41_ff/auen41_ff.py[auen41_ff.py] and turned it into a library that can be imported and run from Swift/T.  The new function entry point is +go()+.  The program still works from the command line

https://github.com/ECP-CANDLE/Supervisor/blob/master/workflows/auen41_ff/py-keras.swift[py-keras.swift] simply loads the module +auen41_ff+ and runs +go()+.

The +go()+ function accepts the directory containing the +breast.train.csv+ and +breast.test.csv+ files.  These can be obtained on Cooley at +~wozniak/Public/data/CANDLE/auen41_ff+ .

The run script that you launch is https://github.com/ECP-CANDLE/Supervisor/blob/master/workflows/auen41_ff/py-keras-cooley.sh[py-keras-cooley.sh] .  The only non-trivial thing here is that we have to set +PYTHONHOME+ for Keras but we cannot let +qsub+ see this variable (or it will fail), so we hide it as +PH+, and send it to Swift via +swift-t -e+.

This obtains settings from https://github.com/ECP-CANDLE/Supervisor/blob/master/workflows/auen41_ff/settings.sh[settings.sh], including +QUEUE+, +PROJECT+, etc.

Output goes in numbered directories +out-NNN+.

==== Example transcript

----
$ ./py-keras-cooley.sh ~wozniak/Public/data/CANDLE/auen41_ff
TURBINE-COBALT SCRIPT
...
JOB_ID=...
... # Job runs...
TOTAL_TIME=...
# Job completed
# View output:
$ less out-001/output.txt
----

== p1b1_hyperopt

The P1B1 hyperopt workflow evaluates a modified version of the P1B1 benchmark autoencoder using hyperparameters provided by a hyperopt instance. The P1B1 code (p1b1_baseline.py) has been modified to expose a functional interface. The neural net remains the same. Currently, hyperopt minimizes the validation loss.

See https://github.com/ECP-CANDLE/Supervisor/tree/master/workflows/p1b1_hyperopt for more details.

== p1b1_mlrMBO

The P1B1 mlrMBO workflow evaluates a modified version of the P1B1 benchmark autoencoder using hyperparameters provided by a mlrMBO instance. The P1B1 code (p1b1_baseline.py) has been modified to expose a functional interface. The neural net remains the same. Currently, mlrMBO minimizes the validation loss.

See https://github.com/ECP-CANDLE/Supervisor/tree/master/workflows/p1b1_mlrMBO for more details.
