# CFG PRM 1

# GA settings

# Total iterations
SEED=${SEED:-1}
NUM_ITERATIONS=${NUM_ITERATIONS:-2}
NUM_VARIATIONS=${NUM_VARIATIONS:-1}
POPULATION_SIZE=${POPULATION_SIZE:-2}
PARAM_SET_FILE=${PARAM_SET_FILE:-$EMEWS_PROJECT_ROOT/data/ga_params.json}
GA_STRATEGY=${STRATEGY:-simple}
MODEL_NAME="combo"
