
== Async Local

A straightforward implementation of a skopt workflow
that runs everything in a Python subprocess.

Uses asynchronous background processes for tasks.

Works fine with aprun on Theta.

== Overview

. The search algorithm is set up using the normal skopt API.
. The workflow starts points_init tasks
. As each task exits, it is replaced by a new one from skopt
. When points_max tasks have been issued, the workflow issues
  no more tasks, but waits for the outstanding ones to complete.
. If any task fails (non-zero exit code), the workflow issues
  no more tasks, but waits for the outstanding ones to complete.
  It also may print a Python stack trace.

== Implementation notes

These details will change rapidly as the workflow becomes more generic.

. If OUTPUT is in the environment, this is used as an output directory,
  else the workflow uses $PWD .
. The workflow tasks are each assigned a unique integer number.
. The output for each task goes to a file with the given number in
  the output directory.

== File index

main.sh::
Shell interface for the Python program.

main.py::
The main Python program.
Sets up and runs the search loop.

Task.py::
The Python task (objective function).
Currently hard-coded to run task.sh.
Needs to become a plug-in.

Problem.py::
The bounding box for the skopt search.
Needs to become a plug-in.

task.sh::
A dummy task.
Can be replaced by any shell script, including the ff Horovod script.

utils.py::
Misc. Python utilities.

=== System-specific scripts

submit-theta.sh::
Submits main.sh on Theta

== Concepts

NODES::
The number of nodes in the allocation

Task::
An execution of the objective function in the search

PARALLELISM::
The number of nodes in each task

CONCURRENCY::
The number of (parallel) tasks running at a point in time

== Sample output

----
$ ./main.sh
search start:
started:  16586
started:  16587
started:  16592
TASK: 16586
  drop           0.3690935629679824
  batch_size     256
delay 2

TASK: 16587
started:  16601
tasks_running:  4
  drop           0.8395811989630504
  batch_size     32
delay 1

TASK: 16592
  drop           0.6031331534420412
  batch_size     64
delay 1

TASK: 16601
  drop           0.31583820140922964
  batch_size     256
delay 0

started:  16630
tasks_running:  4
TASK: 16630
  drop           0.7536495199979558
  batch_size     512
delay 1

started:  16641
tasks_running:  4
TASK: 16641
  drop           0.40034926107103663
  batch_size     512
delay 1

started:  16652
tasks_running:  4
TASK: 16652
  drop           0.731156389521627
  batch_size     32
delay 0

started:  16663
tasks_running:  4
TASK: 16663
  drop           0.7195980974464558
  batch_size     64
delay 1

tasks_running:  3
tasks_running:  2
tasks_running:  1
tasks_running:  0
Workflow complete!
----
