#!/bin/bash
set -eu

LEAVEOUT_CELL_LINE=$1
LEAVEOUT_DRUG=$2
FILE_OUTPUT=$3

echo FAKE-NT3.SH: \
     LEAVEOUT_CELL_LINE=$LEAVEOUT_CELL_LINE \
     LEAVEOUT_DRUG=$LEAVEOUT_DRUG \
     FILE_OUTPUT=$FILE_OUTPUT | \
  tee $FILE_OUTPUT
