
== HPO Table

Creates a CSV file from a collection of `model.log` files.

=== Data format

Supervisor creates an output directory such as `/path/to/Output/EXP002`.

Inside `EXP002`, there are subdirectories `run_I_J_K` where `I` is the optimizer run, `J` is the optimization iteration number, and `K` is the sample number within that iteration.

Inside each `run_I_J_K`, there is a `model.log` that is the `stdout` of Supervisor's `model_runner.py`.  It contains run metadata, hyperparameters, timing, and output metrics.  When running in Singularity, `stdout` from the model is redirected elsewhere.  In a non-Singularity run, the model output is captured here as well.

Additionally, `stdout` from the workflow on a per-rank basis may be found in `/path/to/Output/EXP002/out/out-\*.txt`.  Any output from `workflow.swift` (e.g., output from Swift/T's `printf()`)is found in these per-rank files.  A summary from DEAP is reported in the 2nd-highest-rank `out-*.txt`.

The output CSV header is:

----
iteration,sample,<HYPERPARAMETERS>,metric,result,walltime
----

for example:

----
iteration,sample,learning_rate,batch_size,metric,result,walltime
----

The output CSV data has the following format for LGBM:

----
iteration,sample,learning_rate,metric,result,walltime
001,0000,0.35935086615047446,0,val_loss,0.009126724756649347,13
001,0001,0.9403987611761238,0,val_loss,0.012431074177045679,10
001,0002,0.26630100118913236,0,val_loss,0.008143043197684443,13
002,0000,0.36600957028357706,0,val_loss,0.008470928185503029,11
002,0001,0.9403987611761238,0,val_loss,0.012431074177045679,9
...
----

=== Usage

If `E` is the experiment directory (`EXP002` above), and `hpo.csv` is the desired output file, run:

----
$ ./hpo_table.py -p learning_rate,batch_size $E $E/hpo.csv
----

to store the CSV in the experiment directory.

See also:

----
$ ./hpo_table.py -h
----

== HPO Grab

Copies HPO outputs into the Hall of Fame.  Use one of these depending on whether you are using `CANDLE_MODEL_IMPL=container` (Singularity) or `CANDLE_MODEL_IMPL=py` (plain Python).

----
$ hpo-grab-container.sh HOF MODEL SIZE PARAMS D1 D2 DATASET RANK
# or
$ hpo-grab-py.sh HOF MODEL SIZE PARAMS D DATASET RANK
----

HOF::
The HallOfFame clone

MODEL::
The model name, e.g., `GraphDRP`

SIZE::
The size from the Hall of Fame standard, e.g., `SMALL`

PARAMS::
The HPO params to extract for `hpo.csv`, e.g., `batch_size,learning_rate`

D1::
The Supervisor output directory, e.g., `CANDLE_DATA_DIR/output/GraphDRP/EXP039`

D2::
The Singularity output directory, e.g., `CANDLE_DATA_DIR/GraphDRP/Output/EXP039`

D::
The main output directory, e.g., `experiments/EXP079`

DATASET::
The dataset name, e.g., `CCLE`

RANK::
The DEAP rank, which is the 2nd highest rank.  E.g. if `PROCS` is 16 then `RANK` is 14.

== prep.sh

Simple wrapper around IMPROVE containerized `preprocess.sh`.

. Set environment variable `CANDLE_DATA_DIR` - this will be bound in the container to `candle_data_dir`
. Provide the SIF, a model name, the data source, and an output directory in the container under `/candle_data_dir`
. The data source name will be appended to the output directory
+
----
$ scripts/prep.sh <SIF> <model> <data_source> <outdir>
----
+
For example,
+
----
$ scripts/prep.sh /path/to/Uno.sif Uno GDSCv1 /candle_data_dir/HPO/Uno
----
+
will put the preprocessed data in `/candle_data_dir/HPO/Uno/GDSCv1`

You can get a helpful reminder with no arguments: `scripts/prep.sh`

== Random UPF

----
random-upf
----

Creates a random UPF of any size for the UPF workflow.

----
$ ./random-upf -h
2024-08-01 14:53:12 random_upf INFO  RANDOM UPF
usage: random_upf [-h] [-s SEED] count param_set_file output

Makes a random UPF file.

positional arguments:
  count                 number of rows to generate
  param_set_file        the DEAP parameter set file
  output                The output JSON file

optional arguments:
  -h, --help            show this help message and exit
  -s SEED, --seed SEED  random seed
----

You can specify `output` as `/dev/stdout` for debugging.

Usage example:

----
SV/scripts$ ./random-upf -s 32 3 ../workflows/GA/data/uno_param_space-1.json /dev/stdout
2024-08-01 14:50:23 random_upf INFO  RANDOM UPF
2024-08-01 14:50:23 random_upf INFO  SEED: 32
2024-08-01 14:50:23 random_upf INFO  PARAM: 1: Float(learning_rate∈(0.000,0.000)
2024-08-01 14:50:23 random_upf INFO  PARAM: 2: List(batch_size of 8 ints)
2024-08-01 14:50:23 random_upf INFO  PARAM: 3: Constant(epochs=200)
2024-08-01 14:50:23 random_upf INFO  PARAM: 4: Constant(train_ml_data_dir=/candle_data_dir/HPO/Uno_Improve/CCLE)
2024-08-01 14:50:23 random_upf INFO  PARAM: 5: Constant(val_ml_data_dir=/candle_data_dir/HPO/Uno_Improve/CCLE)
2024-08-01 14:50:23 random_upf INFO  PARAM: 6: Constant(test_ml_data_dir=/candle_data_dir/HPO/Uno_Improve/CCLE)
2024-08-01 14:50:23 random_upf INFO  write: /dev/stdout
{"learning_rate": 7.834436206945082e-07, "batch_size": 128, "epochs": 200, "train_ml_data_dir": "/candle_data_dir/HPO/Uno_Improve/CCLE", "val_ml_data_dir": "/candle_data_dir/HPO/Uno_Improve/CCLE", "test_ml_data_dir": "/candle_data_dir/HPO/Uno_Improve/CCLE"}
{"learning_rate": 1.45500422260353e-06, "batch_size": 128, "epochs": 200, "train_ml_data_dir": "/candle_data_dir/HPO/Uno_Improve/CCLE", "val_ml_data_dir": "/candle_data_dir/HPO/Uno_Improve/CCLE", "test_ml_data_dir": "/candle_data_dir/HPO/Uno_Improve/CCLE"}
{"learning_rate": 4.9675623975915665e-06, "batch_size": 16, "epochs": 200, "train_ml_data_dir": "/candle_data_dir/HPO/Uno_Improve/CCLE", "val_ml_data_dir": "/candle_data_dir/HPO/Uno_Improve/CCLE", "test_ml_data_dir": "/candle_data_dir/HPO/Uno_Improve/CCLE"}
----
