#!/bin/sh

# DB HPO INIT
# Shell UI wrapper for db-hpo-init.py

export THIS=$( readlink --canonicalize-existing $( dirname $0 ) )
WORKFLOWS=$(   readlink --canonicalize-existing $THIS/../.. )
XCORR=$WORKFLOWS/xcorr

PYTHONPATH=$XCORR
export PYTHONPATH
python $THIS/db-cplo-init.py $*
