#!/bin/sh

# DB CPLO INIT
# Shell UI wrapper for db-cplo-init.py

export THIS=$( readlink --canonicalize-existing $( dirname $0 ) )
WORKFLOWS=$(   readlink --canonicalize-existing $THIS/../.. )
CANDLE_SQL=$WORKFLOWS/common/db

PYTHONPATH=$CANDLE_SQL
export PYTHONPATH
python $THIS/db-cplo-init.py $*
