#!/bin/bash
set -eux

# RUN
# Quickly test all Python/sqlite3 operations

DB=xcorr.db

rm -fv $DB

which python sqlite3

python db-init.py
python db-insert-junk.py

sqlite3 $DB "select * from records;"
