# CFG PRM 1

# mlrMBO settings

# Total iterations
PROPOSE_POINTS=${PROPOSE_POINTS:-400}
MAX_CONCURRENT_EVALUATIONS=${MAX_CONCURRENT_EVALUATIONS:-400}
MAX_ITERATIONS=${MAX_ITERATIONS:-5}
MAX_BUDGET=${MAX_BUDGET:-2000}
DESIGN_SIZE=${DESIGN_SIZE:-400}
PARAM_SET_FILE=${PARAM_SET_FILE:-$EMEWS_PROJECT_ROOT/data/hps_space.R}
MODEL_NAME="combo"



