
# CFG PRM 1A

# mlrMBO settings
MAX_BUDGET=${MAX_BUDGET:-1800}
# Total iterations
MAX_ITERATIONS=${MAX_ITERATIONS:-4}
DESIGN_SIZE=${DESIGN_SIZE:-14}
PROPOSE_POINTS=${PROPOSE_POINTS:-14}
PARAM_SET_FILE=${PARAM_SET_FILE:-$EMEWS_PROJECT_ROOT/data/parameter_set_test_1.R}
MODEL_NAME="nt3"
