
# CFG PRM 1

# mlrMBO settings
MAX_BUDGET=${MAX_BUDGET:-1800}
# Total iterations
MAX_ITERATIONS=${MAX_ITERATIONS:-4}
DESIGN_SIZE=${DESIGN_SIZE:-30}
PROPOSE_POINTS=${PROPOSE_POINTS:-30}
PARAM_SET_FILE=${PARAM_SET_FILE:-$EMEWS_PROJECT_ROOT/data/parameter_set3.R}
MODEL_NAME="nt3"
# pbalabra:
# PARAM_SET_FILE="$EMEWS_PROJECT_ROOT/data/parameter_set1.R"
