
# CFG PRM 1

# mlrMBO settings
MAX_BUDGET=${MAX_BUDGET:-8}
# Total iterations
MAX_ITERATIONS=${MAX_ITERATIONS:-4}
DESIGN_SIZE=${DESIGN_SIZE:-8}
PROPOSE_POINTS=${PROPOSE_POINTS:-8}
PARAM_SET_FILE=${PARAM_SET_FILE:-$EMEWS_PROJECT_ROOT/data/parameter_set_test_1.R}
MODEL_NAME="nt3"
