
# CFG PRM 1

# mlrMBO settings
MAX_BUDGET=${MAX_BUDGET:-1800}
# Total iterations
MAX_ITERATIONS=${MAX_ITERATIONS:-2}
DESIGN_SIZE=${DESIGN_SIZE:-10}
PROPOSE_POINTS=${PROPOSE_POINTS:-10}
PARAM_SET_FILE=${PARAM_SET_FILE:-$EMEWS_PROJECT_ROOT/data/parameter_set_test_1.R}
MODEL_NAME="nt3"
