
////
Accessible at:
https://ecp-candle.github.io/Supervisor/home.html
You can compile this locally with:
$ ./adoc.sh README.adoc
////

////
This prevents ^M from appearing in the output:
////
:miscellaneous.newline: \n

:toc:

= CANDLE Supervisor Home Page

This is the main home page about CANDLE Supervisor effort with links to workflows and other supporting information.

== Key deadlines

1. May 15: End-to-end demo of hyperparameter harness
2. June 5-9: ANL hackathon and Theta reservation

== Workflows

The workflows are currently indexed in the README visible https://github.com/ECP-CANDLE/Supervisor/tree/master/workflows[here].

== Database integration

The database work is described in the README visible https://github.com/ECP-CANDLE/Database[here].

== Swift installations

* http://swift-lang.github.io/swift-t/sites.html#_theta[Theta]
+
This is linked to Python and R but currently without ML libs.
+
Other Theta ESP notes are here: https://collab.cels.anl.gov/display/ESP

* http://swift-lang.github.io/swift-t/sites.html#_cori[Cori]
+
This uses the system-installed Python with ML libs at: +
+/usr/common/software/python/2.7-anaconda/envs/deeplearning+

[[titan]]
* https://www.olcf.ornl.gov/titan[Titan]
+
This is a CANDLE-only installation.  It uses the OLCF-provided Python  +deeplearning+ module (Python 3.6 plus TensorFlow, Theano, and Keras) and R 3.3.2 .
+
Add to +PATH+: +/lustre/atlas2/csc249/proj-shared/sfw/swift-t/stc/bin+
+
Run with:
+
----
$ export TITAN=true
$ export PROJECT=... QUEUE=...
$ export LD_LIBRARY_PATH=/sw/xk6/deeplearning/1.0/sles11.3_gnu4.9.3/lib:/sw/xk6/deeplearning/1.0/sles11.3_gnu4.9.3/cuda/lib64:/opt/gcc/4.9.3/snos/lib64:/sw/xk6/r/3.3.2/sles11.3_gnu4.9.3x/lib64/R/lib
$ swift-t -m cray -e LD_LIBRARY_PATH=$LD_LIBRARY_PATH workflow.swift
----

* http://swift-lang.github.io/swift-t/sites.html#cooley_candle[Cooley]
+
This uses the system-installed Python with ML libs at: +
+/soft/analytics/conda/env/Candle_ML+

* http://swift-lang.github.io/swift-t/sites.html#_jlse_knl[JLSE KNL]
+
This does not yet have Python.

* JLSE Prasanna +
This uses a VirtualEnv Python at +/home/pbalapra/.virtualenvs+
** +~wozniak/Public/sfw/icc/swift-t-pb/stc/bin+
