
= Fake LBANN Interface

Goal: Generate a Python interface for a fake LBANN library, call it from a C program.

. The C program is py-eval
. The Python interface is generated by SWIG
. The fake LBANN library is assumed to exist

== Quick start

. Edit Makefile to setup mpicc and Python
. Build
+
----
$ make
----
+
. Run
+
----
$ export PYTHONPATH=$PWD
$ mpiexec -n 2 -l py-eval test_1.py 0
----

== File index

=== Fake LBANN (FL)

This is assumed to exist in advance.

fl.h::

fl.c::
Defines a function that accepts a communicator, a subset of MPI_COMM_WORLD, and can run MPI on it

=== Fake LBANN interface

fl_interface.i::
The SWIG interface file

fl_interface.[hc]::
A glue layer to accept an integer from the parent environment and convert it to an MPI_Comm for FL

=== The workflow layer

test_1.py::
A Python fragment that can call the FL interface

py-eval::
See the https://github.com/ECP-CANDLE/Supervisor/tree/develop/scratch/py-eval[py-eval docs] +
py-eval sets the environment variable COMM for use by MPI tasks inside it
