
= Mini Challenge Problem workflow

Currently, this uses a mix of xcorr and cp1.

== Quick Start

Run the workflow in +workflows/cp1+

=== Data

==== Studies files

* data/studies[12].txt
+
One study name per line.  This file can have # comments

==== RNA files

* combined_rnaseq_data_combat
* data/rnaseq-small.txt
+ Each line starts with a STUDY.SUBJECT token followed by the RNA data +
  for each feature

==== Features files

The list of feature names



==== Cross-correlation data



----
$ wget http://www.mcs.anl.gov/~wozniak/candle-cp1-data.tgz
$ tar xfz candle-cp1-data.tgz
----

This will create a directory called xcorr_data

This data was retrieved by Wozniak from Summit directory +
/gpfs/alpine/med106/scratch/ncollier/xcorr_data +
on April 24, 2019.

==== Big data

The full RNA sequence data set is here:

----
$ cd data
$ wget http://ftp.mcs.anl.gov/pub/candle/public/benchmarks/Pilot1/combo/combined_rnaseq_data_combat
----

==== Small data

Use the script data/make-small-data.sh

=== Execution

----
$ cd test
# edit cfg-* as necessary
$ ./test-1.sh theta -a
----

=== Doing a small run

. Edit data/studies[12].txt to select two different studies (one pair)
. Edit your cfg-sys file to set TURBINE_RESIDENT_WORK_WORKERS to the number of pairs


=== Summit Notes

Summit's project directories (e.g. /ccs/proj/med106/) are not writable from the compute nodes.
The workflow needs the following directories in Supervisor/workflows/cp1 to be writable.

* cache
* experiments
* xcorr_data

One solution is to symlink them from a writable location such as /gpfs/alpine/med106/scratch.
For example,

----
$ pwd
/ccs/proj/med106/ncollier/repos/Supervisor/workflows/cp1
$ ls -l
lrwxrwxrwx 1 ncollier ncollier   46 Mar  1 10:35 cache -> /gpfs/alpine/med106/scratch/ncollier/uno_cache
lrwxrwxrwx 1 ncollier ncollier   48 Feb 28 16:51 experiments -> /gpfs/alpine/med106/scratch/ncollier/experiments
lrwxrwxrwx 1 ncollier ncollier   47 Mar  1 12:38 xcorr_data -> /gpfs/alpine/med106/scratch/ncollier/xcorr_data
----


=== More Details

 TODO
...
