#!/bin/bash
#
# Usage: ./run 
#

if [ "$#" -ne 1 ]; then
  script_name=$(basename $0)
  echo "Usage: ${script_name} EXPERIMENT_ID (e.g. ${script_name} experiment_1)"
  exit 1
fi

#### set this variable to your P1B1 benchmark directory (frameworks branch)
P1B1_DIR=../../../../Benchmarks/Pilot1/P1B1
###

# Resident task workers and ranks
export TURBINE_RESIDENT_WORK_WORKERS=1
export RESIDENT_WORK_RANKS=$(( PROCS - 2 ))

THIS=$( cd $( dirname $0 ); /bin/pwd )
export APP_HOME=$THIS

PROJECT_ROOT=$APP_HOME/..

export PYTHONPATH=$PYTHONPATH:$PROJECT_ROOT/python:$P1B1_DIR:$PROJECT_ROOT/../common/python:$PYTHONPATH

export EXPID=$1
export TURBINE_OUTPUT=$APP_HOME/../experiments/$EXPID


# TODO edit QUEUE, WALLTIME, PPN, AND TURNBINE_JOBNAME
# as required. Note that QUEUE, WALLTIME, PPN, AND TURNBINE_JOBNAME will
# be ignored if MACHINE flag (see below) is not set
export QUEUE=batch
export WALLTIME=00:10:00
export PPN=16
export TURBINE_JOBNAME="${EXPID}_job"

echo $PYTHONPATH

### set the desired number of processors
PROCS=8
###

# remove -l option for removing printing processors ranks
# settings.json file has all the parameter combinations to be tested
echo swift-t  -n $PROCS $APP_HOME/random-sweep.swift $*
swift-t  -l -n $PROCS $APP_HOME/random-sweep.swift $* --settings=$PWD/../data/settings.json 